import {
  bandcampEmbedUrlPatternSource,
  internalOrHttpsUrlPatternSource,
  tidalContentUrlPatternSource,
} from '../editorial-validation';
import { buildField, buildFieldMapping, buildFolderCollection } from './decap-yaml-builder';
import { decapCollectionDescriptions } from './decap-editorial-copy';
import { decapCollectionMedia } from './decap-media';

export function buildReleaseCollection() {
  return buildFolderCollection({
    name: 'releases',
    label: 'Releases',
    description: decapCollectionDescriptions.releases,
    labelSingular: 'Release',
    previewPath: 'releases/{{slug}}/',
    sortableFields: ['release_date', 'title', 'artist', 'commit_date'],
    folder: 'apps/web/src/content/releases',
    create: true,
    delete: false,
    extension: 'md',
    format: 'frontmatter',
    identifierField: 'title',
    slug: '{{slug}}',
    mediaFolder: decapCollectionMedia.releases.mediaFolder,
    publicFolder: decapCollectionMedia.releases.publicFolder,
    summary: '{{release_date}} — {{title}} — {{artist}}',
    fields: [
      buildField({ label: 'Title', name: 'title', widget: 'string', hint: 'Release title.' }),
      buildField({
        label: 'Artist',
        name: 'artist',
        widget: 'relation',
        hint: 'Search the current Artists collection. The saved value is the Artist slug used by Astro references.',
        relation: {
          collection: 'artists',
          searchFields: ['title', 'slug'],
          valueField: 'slug',
          displayFields: ['title', 'slug'],
          optionsLength: 50,
        },
      }),
      buildField({
        label: 'Release date',
        name: 'release_date',
        widget: 'datetime',
        hint: 'Official release date used by the public site for display and release ordering/latest behavior. Time is ignored. Example: 2026-09-18.',
        extras: ['date_format: YYYY-MM-DD', 'time_format: false'],
      }),
      buildField({
        label: 'Cover image',
        name: 'cover_image',
        widget: 'image',
        hint: 'Primary square cover artwork used in release cards, detail views, and Store Item projection.',
      }),
      buildField({
        label: 'Cover image alt',
        name: 'cover_image_alt',
        widget: 'string',
        required: true,
        hint: 'Required. Describe the visible artwork, colors, and central subject rather than repeating only the release title.',
      }),
      buildField({
        label: 'Merch URL',
        name: 'merch_url',
        widget: 'string',
        required: false,
        hint: 'Optional internal Store path or full HTTPS product URL. Example: /store/ or https://example.com/product.',
        pattern: {
          value: internalOrHttpsUrlPatternSource,
          message: 'Use an internal path beginning with / or a full HTTPS URL.',
        },
      }),
      buildField({
        label: 'Bandcamp embed URL',
        name: 'bandcamp_embed_url',
        widget: 'string',
        required: false,
        hint: 'Paste the iframe src from Bandcamp Share/Embed, not the public album or track page URL.',
        pattern: {
          value: bandcampEmbedUrlPatternSource,
          message: 'Use the official Bandcamp album or track iframe src.',
        },
      }),
      buildField({
        label: 'Tidal URL',
        name: 'tidal_url',
        widget: 'string',
        required: false,
        hint: 'Full Tidal album, track, playlist, or video URL including https://. Artist profile URLs are not embedded players.',
        pattern: {
          value: tidalContentUrlPatternSource,
          message: 'Use a Tidal album, track, playlist, or video URL.',
        },
      }),
      buildField({
        label: 'Summary',
        name: 'summary',
        widget: 'text',
        required: false,
        hint: 'Short release summary shown in cards and detail headers.',
      }),
      buildField({
        label: 'Formats',
        name: 'formats',
        widget: 'list',
        required: false,
        labelSingular: 'Format',
        hint: 'Physical or digital formats shown in the release detail UI.',
        collapsed: true,
        summary: '{{fields.value}}',
        allowAdd: true,
        allowRemove: true,
        allowReorder: true,
        field: buildFieldMapping({
          label: 'Format',
          name: 'value',
          widget: 'string',
          hint: 'Example: "LP", "CD", or "Digital".',
        }),
      }),
      buildField({
        label: 'Credits',
        name: 'credits',
        widget: 'list',
        required: false,
        labelSingular: 'Credit',
        hint: 'Role/name credit pairs shown in the release detail.',
        collapsed: true,
        summary: '{{fields.role}} — {{fields.name}}',
        allowAdd: true,
        allowRemove: true,
        allowReorder: true,
        fields: [
          buildField({ label: 'Role', name: 'role', widget: 'string', hint: 'Example: "Mastering" or "Artwork".' }),
          buildField({ label: 'Name', name: 'name', widget: 'string', hint: 'Person or studio name.' }),
        ],
      }),
    ],
  });
}
