import { buildField, buildFieldMapping, buildFolderCollection, type DecapSelectOption } from './decap-yaml-builder';
import { decapCollectionDescriptions } from './decap-editorial-copy';

export function buildReleaseCollection(artistOptions: DecapSelectOption[]) {
  return buildFolderCollection({
    name: 'releases',
    label: 'Releases',
    description: decapCollectionDescriptions.releases,
    folder: 'apps/web/src/content/releases',
    create: true,
    delete: true,
    extension: 'md',
    format: 'frontmatter',
    identifierField: 'title',
    mediaFolder: '.',
    publicFolder: './',
    summary: '{{title}} - {{artist}}',
    fields: [
      buildField({ label: 'Title', name: 'title', widget: 'string', hint: 'Release title.' }),
      buildField({
        label: 'Artist',
        name: 'artist',
        widget: 'select',
        hint: 'Pick the matching artist entry so Astro references stay valid.',
        options: artistOptions,
      }),
      buildField({
        label: 'Release date',
        name: 'release_date',
        widget: 'datetime',
        hint: 'Official release date used by the public site for display and release ordering/latest behavior. Time is ignored. Example: 2026-09-18.',
        extras: ['date_format: YYYY-MM-DD', 'time_format: false'],
      }),
      buildField({
        label: 'Cover image',
        name: 'cover_image',
        widget: 'image',
        hint: 'Primary release artwork used in cards and the release detail view.',
      }),
      buildField({
        label: 'Cover image alt',
        name: 'cover_image_alt',
        widget: 'string',
        required: false,
        hint: 'Describe the artwork for screen readers.',
      }),
      buildField({
        label: 'Merch URL',
        name: 'merch_url',
        widget: 'string',
        required: false,
        hint: 'Optional direct merch or product URL. Include https://.',
      }),
      buildField({
        label: 'Bandcamp embed URL',
        name: 'bandcamp_embed_url',
        widget: 'string',
        required: false,
        hint: 'Paste the iframe src from Bandcamp Share/Embed, not the public album or track page URL.',
      }),
      buildField({
        label: 'Tidal URL',
        name: 'tidal_url',
        widget: 'string',
        required: false,
        hint: 'Full Tidal album, track, playlist, or video URL including https://. Artist profile URLs are not embedded players.',
      }),
      buildField({
        label: 'Summary',
        name: 'summary',
        widget: 'text',
        required: false,
        hint: 'Short release summary shown in cards and detail headers.',
      }),
      buildField({
        label: 'Formats',
        name: 'formats',
        widget: 'list',
        required: false,
        hint: 'Physical or digital formats shown in the release detail UI.',
        collapsed: true,
        summary: '{{fields.value}}',
        field: buildFieldMapping({
          label: 'Format',
          name: 'value',
          widget: 'string',
          hint: 'Example: "LP", "CD", or "Digital".',
        }),
      }),
      buildField({
        label: 'Credits',
        name: 'credits',
        widget: 'list',
        required: false,
        hint: 'Role/name credit pairs shown in the release detail.',
        collapsed: true,
        summary: '{{fields.role}}',
        fields: [
          buildField({ label: 'Role', name: 'role', widget: 'string', hint: 'Example: "Mastering" or "Artwork".' }),
          buildField({ label: 'Name', name: 'name', widget: 'string', hint: 'Person or studio name.' }),
        ],
      }),
    ],
  });
}
