import type { InternalOrder } from '../../lib/backend/internal-order-api';

export const exampleOrder: InternalOrder = {
  checkoutExpiresAt: '2026-09-11T15:00:00.000Z',
  checkoutSessionId: 'cs_test_example',
  createdAt: '2026-09-11T12:00:00.000Z',
  updatedAt: '2026-09-11T12:05:00.000Z',
  statusUpdatedAt: '2026-09-11T12:05:00.000Z',
  paidAt: '2026-09-11T12:05:00.000Z',
  notPaidAt: null,
  needsReviewAt: null,
  needsReviewReason: null,
  status: 'paid',
  storeItemSlug: 'example-lp',
  variantId: 'example-vinyl',
  stripePaymentIntentId: 'pi_test_example',
  monetaryPolicyReference: null,
  acceptedDeliveryAmountMinor: null,
  acceptedParcelTier: null,
  shippingLocker: null,
  deliveries: [
    {
      kind: 'ops_fulfillment',
      status: 'delivered',
      attemptCount: 1,
      createdAt: '2026-09-11T12:05:00.000Z',
      updatedAt: '2026-09-11T12:06:00.000Z',
      deliveredAt: '2026-09-11T12:06:00.000Z',
      nextAttemptAt: null,
      needsReviewAt: null,
      safeReason: null,
    },
  ],
  fulfillment: {
    kind: 'current',
    amountTotalMinor: 3200,
    currencyCode: 'EUR',
    deliveryGrossMinor: 400,
    deliveryVatMinor: null,
    merchandiseGrossMinor: 2800,
    totalVatMinor: null,
    paidAt: '2026-09-11T12:05:00.000Z',
    recipientName: 'Example recipient',
    shopperContact: { email: 'example@example.invalid', phone: null },
    shippingAddress: {
      line1: 'Example street',
      line2: null,
      postalCode: '10000',
      city: 'Athens',
      state: null,
      country: 'GR',
    },
    newsletterConsent: { optedIn: false },
    lines: [
      {
        displayName: 'Example LP',
        optionLabel: 'Black vinyl',
        quantity: 1,
        unitAmountMinor: 2000,
        lineAmountMinor: 2000,
        lineVatMinor: null,
        taxRatePercent: null,
        storeItemSlug: 'example-lp',
        variantId: 'example-vinyl',
      },
      {
        displayName: 'Example tape',
        optionLabel: 'Cassette',
        quantity: 1,
        unitAmountMinor: 800,
        lineAmountMinor: 800,
        lineVatMinor: null,
        taxRatePercent: null,
        storeItemSlug: 'example-tape',
        variantId: 'example-cassette',
      },
    ],
  },
};
